# Generated by Django 3.1.2 on 2020-11-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
