# Generated by Django 3.1.2 on 2020-11-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
