# Generated by Django 3.1.2 on 2020-11-10 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201109_1713'),
        ('base', '0002_auto_20201109_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.line'),
        ),
    ]
