# Generated by Django 3.1.2 on 2020-11-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_moment_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='possible_line',
            field=models.TextField(blank=True),
        ),
    ]
