# Generated by Django 3.1.2 on 2020-11-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201113_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='aes1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='aes2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='aes3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='fas1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='fas2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='fas3',
        ),
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
