# Generated by Django 3.1.2 on 2020-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201117_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='possible_comment',
            field=models.TextField(blank=True),
        ),
    ]
