# Generated by Django 3.1.2 on 2020-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20201118_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
