# Generated by Django 3.1.2 on 2020-11-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='free_response',
            field=models.TextField(default='nonoe'),
            preserve_default=False,
        ),
    ]
