# Generated by Django 3.1.2 on 2021-02-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210129_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='topic',
            field=models.TextField(default='No Summary Provided'),
            preserve_default=False,
        ),
    ]
